In [1]:
ahmad = 199
ali = 299
ahmad * ali

59501

In [2]:
199 * 299

59501

In [3]:
momin = ''' i am 21 years old
i am not a human
i am not not ok.
'''
print(momin)

 i am 21 years old
i am not a human
i am not not ok.



In [4]:
mominStake = " he can't fly.  But he surely can say: \"Go\" " 

In [5]:
mominStake = " he can't fly.  But he surely can say: \"Go\" " 
print(mominStake)

 he can't fly.  But he surely can say: "Go" 


In [6]:
score1 = 99
scoreCard = "Ahmad's score is %s"
print(scoreCard %s score1)
score2 = 89
print("All score are %s %s" % (score1,score2))


SyntaxError: invalid syntax (3567343702.py, line 3)

In [7]:
score1 = 99
scoreCard = "Ahmad's score is %s"
print(scoreCard % score1)
score2 = 89
print("All score are %s %s" % (score1,score2))


Ahmad's score is 99
All score are 99 89


In [8]:
print("sorry "*10)

sorry sorry sorry sorry sorry sorry sorry sorry sorry sorry 


In [9]:
rateList = [13,15,19,21]
rateList.append(29)
print(rateList)
del rateList[2]
print(rateList)

[13, 15, 19, 21, 29]
[13, 15, 21, 29]


In [10]:
rateList = [13,15,19,21]
list= ["apple","peach"]
final=(rateList+list)
print(final)

[13, 15, 19, 21, 'apple', 'peach']


In [11]:
list= ["apple","peach"]
print(list*2)

['apple', 'peach', 'apple', 'peach']


In [14]:
map1 = {"apple":100 , "peach":200}
print(map1)
map1["apple"]=110
print(map1)
map1["Banana"]=150
print(map1)
del map1["apple"]
print(map1)

{'apple': 100, 'peach': 200}
{'apple': 110, 'peach': 200}
{'apple': 110, 'peach': 200, 'Banana': 150}
{'peach': 200, 'Banana': 150}


In [15]:
rateList = [13,15,19,21]
rateList.append(29)
print(rateList[0:3])

[13, 15, 19]


In [2]:
age = 21
if age > 23:
    print("Older")
else:
    print("Younger")

Younger


In [3]:
age = None
if age == None:
    print("Impossible")


Impossible


In [1]:
x = 45 
y = 95 

while x < 50 and y < 100: 
    x = x + 1 
    y = y + 1 
    print('x = %s , y = %s'%(x,y)) 

list = ['name1','name2'] 
for x in list: 
    print("value = %s" %x) 

x = 46 , y = 96
x = 47 , y = 97
x = 48 , y = 98
x = 49 , y = 99
x = 50 , y = 100
value = name1
value = name2


In [2]:
variable3 = 23 
def mulOp(): 
    var1 = 2 
    return var1 * variable3 
print(mulOp()) 

import time 
print(time.asctime()) 

46
Tue Aug 16 22:19:13 2022


In [8]:
for x in range(0,5):
    print('value No.%s'%x)

value No.0
value No.1
value No.2
value No.3
value No.4


In [7]:
import scikitl as n

ModuleNotFoundError: No module named 'scikitl'

In [7]:
class Shape():
    typeOfObject = "boundry"
    def __init__(self):
        print('it is a shape')
    def behaviour():
        return 'Measurable'
class animal():
    pass
        
class Circle(Shape):
    #class attribute
    pi = 3.14
    #constructor
    def __init__(self,radius):
        self.radius = radius
    
    #speacial Methods
    
    def __str__(self):
        return "Type Of Object : {} \nBehaviour: {} \nConstant : {} \nRadius: {} \n".format(Shape.typeOfObject,Shape.behaviour(),Circle.pi,self.radius)

    def __len__(self):
        return self.radius
    
    #Non-Static Methods
    def calculateArea(self):
        return self.radius**2 * Circle.pi
    

    def setRadius(self,radius):
        self.radius = radius

    # Use Inherited Methods    
    def details(self):
        print("type of object: %s"%super().typeOfObject)
        print("Behaviour: {}".format(Shape.behaviour())) 
c1 = Circle(3)
print(dir())

['Circle', 'In', 'Out', 'Shape', '_', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_ih', '_ii', '_iii', '_oh', 'animal', 'c1', 'exit', 'get_ipython', 'quit']


In [3]:
print(abs(-10))

10


In [2]:
try:
    1/0
except(ZeroDivisionError):
    print("AN exception occured")
    

AN exception occured


In [3]:
%%writefile myfile.txt
i am going to learn some extra bits

Writing myfile.txt


In [4]:
file = open()

TypeError: open() missing required argument 'file' (pos 1)

In [6]:
pwd

'C:\\Users\\Momin-PC'

In [7]:
list2 = [oneTerm for oneTerm in range(4,8) if oneTerm%2 == 0 ]
print(list2)

[4, 6]


In [21]:
list2.reverse()
print(list2)
#help(list2.reverse())

[6, 4]


In [23]:
a = b = c = 'momhh' , True , 89
print(a,b,c)

('momhh', True, 89) ('momhh', True, 89) ('momhh', True, 89)


In [26]:
list3 = [x for x in range(15,23)]
for ind,num in enumerate(list3):
    print('The number is',num,'and the index is',ind)

The number is 15 and the index is 0
The number is 16 and the index is 1
The number is 17 and the index is 2
The number is 18 and the index is 3
The number is 19 and the index is 4
The number is 20 and the index is 5
The number is 21 and the index is 6
The number is 22 and the index is 7


In [38]:
list3 = [x for x in range(15,23)]
print(list3)

[15, 16, 17, 18, 19, 20, 21, 22]


In [39]:
def addIntoList(ourList,ourElement):
    ourList.append(ourElement)
    print(ourElement,'has been added into List')
    return ourList
print(addIntoList(list3,39))


39 has been added into List
[15, 16, 17, 18, 19, 20, 21, 22, 39]


In [40]:

def addAtIndexInList(ourList,ourIndex,ourElement):
    ourList.insert(ourIndex,ourElement)
    print(ourElement,'has been added at location',ourIndex,'into List')
    return ourList
print(addAtIndexInList(list3,5,99))


99 has been added at location 5 into List
[15, 16, 17, 18, 19, 99, 20, 21, 22, 39]


In [42]:
def delAtIndexInList(ourList,ourIndex):
    delElement = ourList.pop(ourIndex)
    print(delElement,'has been deleted from location',ourIndex,'in List')
    return ourList
print(delAtIndexInList(list3,4))

19 has been deleted from location 4 in List
[15, 16, 17, 18, 99, 20, 21, 22, 39]


In [46]:
def delAtIndexInList(ourList,ourIndex):
    assert type(ourIndex) == int ,'the data type of index must be an integer'
    delElement = ourList.pop(ourIndex)
    print(delElement,'has been deleted from location',ourIndex,'in List')
    return ourList
print(delAtIndexInList(list3,5))


20 has been deleted from location 5 in List
[15, 16, 17, 18, 99, 21, 22, 39]


In [67]:
from datetime import datetime as dt
date = dt.now()
date
print(date.year)
print(date.minute)
#format Specifiers
day = date.strftime('%a')
print(day)
print(date.strftime('%H:%M:%S __ %M/%D/%Y'))
#Parse string datetime
date1 = '30 January,2021'
print(dt.strptime(date1,'%d %B,%Y'))
date2 = '30/02/2021'
print(dt.strptime(date2,'%d/%M/%Y'))

2022
26
Mon
20:26:22 __ 26/08/22/22/2022
2021-01-30 00:00:00
2021-01-30 00:02:00


In [75]:
import os
os.getcwd()
ourDir ='Momin-PC'
parentDir = 'C:\\Users'
path = os.path.join(parentDir,ourDir)
os.path.exists(path)

True

In [105]:
import inspect 
sig1 = inspect.signature(delAtIndexInList)
print(sig1)
print(sig1.parameters)
str1 = 'a'
print(inspect.ismethod(str1))
inspect.getmembers(str1)

(ourList, ourIndex)
OrderedDict([('ourList', <Parameter "ourList">), ('ourIndex', <Parameter "ourIndex">)])
False


[('__add__', <method-wrapper '__add__' of str object at 0x000002A23BFFD4F0>),
 ('__class__', str),
 ('__contains__',
  <method-wrapper '__contains__' of str object at 0x000002A23BFFD4F0>),
 ('__delattr__',
  <method-wrapper '__delattr__' of str object at 0x000002A23BFFD4F0>),
 ('__dir__', <function str.__dir__()>),
 ('__doc__',
  "str(object='') -> str\nstr(bytes_or_buffer[, encoding[, errors]]) -> str\n\nCreate a new string object from the given object. If encoding or\nerrors is specified, then the object must expose a data buffer\nthat will be decoded using the given encoding and error handler.\nOtherwise, returns the result of object.__str__() (if defined)\nor repr(object).\nencoding defaults to sys.getdefaultencoding().\nerrors defaults to 'strict'."),
 ('__eq__', <method-wrapper '__eq__' of str object at 0x000002A23BFFD4F0>),
 ('__format__', <function str.__format__(format_spec, /)>),
 ('__ge__', <method-wrapper '__ge__' of str object at 0x000002A23BFFD4F0>),
 ('__getattribute__',

In [5]:
import sqlite3
from sqlite3 import Error

In [6]:
def create_connection(db_file):
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print('Connection is ON With DB : ',db_file)
        return conn
    except Error as e:
         print(e)

In [7]:
def close_connection(conn):
    if(conn):
        conn.close()
        print('Connection is OFF')

In [8]:
def create_table_in_db(conn,create_table_sql):
    try:
        c = conn.cursor()
        c.execute(create_table_sql)
        print('Table has been created for conn : ',conn)
    except Error as e:
        print(e)

In [10]:
#Task Create a Table:
def create_table():
    database = r"E:\\Python\\temp\\ostempdir\\database.db"
    sql_create_projects_table = """ CREATE TABLE IF NOT EXISTS STUDENTS(
    id integer PRIMARY KEY,
    name text NOT NULL,
    gpa integer,
    admission_date text
    );
    """
    #create connection
    conn = create_connection(database)
    
    #check connection
    if conn is not None:
        #create table
        create_table_in_db(conn,sql_create_projects_table)
    else:
        print('Error! cannot create database connection : ',conn )
    close_connection(conn)
    

In [12]:
create_table()

Connection is ON With DB :  C:\\temp\\ostempdir\\database.db
Table has been created for conn :  <sqlite3.Connection object at 0x000002335C7DCA80>
Connection is OFF


In [14]:
def add_student(conn,student):
    #Using Placeholders
    sql= """INSERT INTO STUDENTS(name,gpa,admission_date)
    VALUES(?,?,?);
    """
    try:
        c = conn.cursor()
        c.execute(sql,student)
        
        return = c.lastrowid
    except Error as e:
        print(e)

In [26]:
#Task , add a student
database = r"E:\\Python\\temp\\ostempdir\\database.db"
 #create connection
conn = create_connection(database)
with conn:
    std = ['ahmad',3,'2022-9-05']
    std_id = add_student(conn,std)
print('The Student ID: ',std_id)
#close connection
close_connection(conn)

Connection is ON With DB :  E:\\Python\\temp\\ostempdir\\database.db
Student has been added into Students with id :  4
The Student ID:  4
Connection is OFF


In [22]:
#Read a table
def read_table(database,table_name):
    sql_script = "SELECT * FROM " + table_name
     #create connection
    conn = create_connection(database)
    try:
        c = conn.cursor()
        c.execute(sql_script)
        
        records = c.fetchall()
        print('Total Records are : ',len(records))
        
        c.close()
    except Error as e:
        print('Failed to read from table : ',table_name ," Error : ",e)
    finally:
        close_connection(conn)
    return records

In [27]:
#Task
database = r"E:\\Python\\temp\\ostempdir\\database.db"
table_name = 'Students'
rec = read_table(database,table_name)
rec

Connection is ON With DB :  E:\\Python\\temp\\ostempdir\\database.db
Total Records are :  4
Connection is OFF


[(1, 'momin', 3.6, '2021-2-15'),
 (2, 'moH', 3.8, '2021-1-15'),
 (3, 'ahad', 2.8, '2022-1-15'),
 (4, 'ahmad', 3, '2022-9-05')]

In [33]:
#CSV MODULE
import csv
fileName =  r"E:\\Python\\csvFile.csv"
data = [(1, 'momin', 3.6, '2021-02-5'),(2, 'moH', 3.8, '2021-01-4'),(3, 'ahad', 2.8, '2022-01-9'),(4, 'ahmad', 3, '2022-9-05')]
#writer handler
writer = csv.writer(open(fileName,'w',newline=''))
#writing
for rec in data:
    writer.writerow(rec)

In [42]:
fileName =  r"E:\\Python\\csvFile.csv"
reader = csv.reader(open(fileName,'r'))
#skip the header of csv file , header has been defined
#header = reader.__next__()
#read
for rec in reader:
    print(rec)             

['1', 'momin', '3.6', '2021-02-5']
['2', 'moH', '3.8', '2021-01-4']
['3', 'ahad', '2.8', '2022-01-9']
['4', 'ahmad', '3', '2022-9-05']


In [46]:
import subprocess as sp
output = sp.check_output("E:\\Python\\dataForSubProcess.py",shell=True)
print(output)
#sp.call("E:\\Python\\dataForSubProcess.py",shell=True)
#work with cmd , using python CodeFile.py

b"['1', 'momin', '3.6', '2021-02-5']\r\n['2', 'moH', '3.8', '2021-01-4']\r\n['3', 'ahad', '2.8', '2022-01-9']\r\n['4', 'ahmad', '3', '2022-9-05']\r\n"


In [47]:
#Exercise:
fileName =  r"C:\\Program Files\\\Mozilla Firefox\\firefox.exe"
sp.call(fileName,shell=True)

0

In [5]:
#Get
import requests as r
x = r.get("https://api.github.com/users/CiphermanAhmad")
print(x.status_code)
#print(x.text)
#print('\n')
#see headers data
#print(x.headers)

#data in key:value pairs
data = x.json()
#print('\n')
print('name  : ',data['name'])
print("location : ",data['location'])
print(data)


200
name  :  Momin
location :  Pakistan
{'login': 'CiphermanAhmad', 'id': 87282236, 'node_id': 'MDQ6VXNlcjg3MjgyMjM2', 'avatar_url': 'https://avatars.githubusercontent.com/u/87282236?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/CiphermanAhmad', 'html_url': 'https://github.com/CiphermanAhmad', 'followers_url': 'https://api.github.com/users/CiphermanAhmad/followers', 'following_url': 'https://api.github.com/users/CiphermanAhmad/following{/other_user}', 'gists_url': 'https://api.github.com/users/CiphermanAhmad/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/CiphermanAhmad/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/CiphermanAhmad/subscriptions', 'organizations_url': 'https://api.github.com/users/CiphermanAhmad/orgs', 'repos_url': 'https://api.github.com/users/CiphermanAhmad/repos', 'events_url': 'https://api.github.com/users/CiphermanAhmad/events{/privacy}', 'received_events_url': 'https://api.github.com/users/CiphermanAhmad/

In [6]:
x = r.head("https://github.com")
#json
#print(x.headers)
print(x.headers['Content-Type'])

text/html; charset=utf-8


In [7]:
#exercise:
url ='https://official-joke-api.appspot.com/jokes/programming/random'
response = r.get(url)
print(response.status_code)
#data = response.json()[0]
#for key in data:
   # print(key," : ",data[key])

500


In [8]:
x = r.head("https://google.com")
print(x.headers)

{'Location': 'https://www.google.com/', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Fri, 26 Aug 2022 13:12:59 GMT', 'Expires': 'Sun, 25 Sep 2022 13:12:59 GMT', 'Cache-Control': 'public, max-age=2592000', 'Server': 'gws', 'Content-Length': '220', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'}


In [9]:
#POST
myObj = [('momin', 3.6),('ahmad','4')]
url ="http://httpbin.org/post"
p = r.post(url,data=myObj)
print(p.text)
data = p.json()
data['form']

{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "ahmad": "4", 
    "momin": "3.6"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Content-Length": "17", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.27.1", 
    "X-Amzn-Trace-Id": "Root=1-6308c6db-6fa5a3b650ffd36f53d751bb"
  }, 
  "json": null, 
  "origin": "182.190.14.158", 
  "url": "http://httpbin.org/post"
}



{'ahmad': '4', 'momin': '3.6'}

In [62]:
#request Modules Exercise 1:
url = "https://dummy.restapiexample.com/api/v1/employees"
response = r.get(url,'text/html')
#print(response.status_code)
#print(response.headers)
#data = response.json()
#print(data)


406
{'id': 1, 'employee_name': 'Tiger Nixon', 'employee_salary': 320800, 'employee_age': 61, 'profile_image': ''}
success


In [183]:
#get data from file becuase of error :406
file = open("E:\\Python\\reqEx1.json",'r')
import json as j
data = j.load(file)

employees = data['data']
print(employees)

for e in employees:
    for key in e:
        print(key,':',e[key])
    print('\n')
    
list1 = []
class employee:
    def __init__(self,id,name,age,salary):
        self.id = id
        self.name = name
        self.age = age
        self.salary = salary
    def __str__(self):
        #return self.name
        return "id : "+str(self.id)+"\nName : "+self.name+"\nAge : "+str(self.age)+"\nSalary : "+str(self.salary)
   
        
#print(data['data'][0]['employee_name'])
for emp in employees:
    id = emp['id']
    name= emp['employee_name']
    age = emp['employee_age']
    salary = emp['employee_salary']
    emp = employee(id,name,age,salary)
    #print(emp)
    list1.append(emp)


[{'id': 1, 'employee_name': 'Tiger Nixon', 'employee_salary': 320800, 'employee_age': 61, 'profile_image': ''}, {'id': 2, 'employee_name': 'Garrett Winters', 'employee_salary': 170750, 'employee_age': 63, 'profile_image': ''}, {'id': 3, 'employee_name': 'Ashton Cox', 'employee_salary': 86000, 'employee_age': 66, 'profile_image': ''}, {'id': 4, 'employee_name': 'Cedric Kelly', 'employee_salary': 433060, 'employee_age': 22, 'profile_image': ''}, {'id': 5, 'employee_name': 'Airi Satou', 'employee_salary': 162700, 'employee_age': 33, 'profile_image': ''}, {'id': 6, 'employee_name': 'Brielle Williamson', 'employee_salary': 372000, 'employee_age': 61, 'profile_image': ''}, {'id': 7, 'employee_name': 'Herrod Chandler', 'employee_salary': 137500, 'employee_age': 59, 'profile_image': ''}, {'id': 8, 'employee_name': 'Rhona Davidson', 'employee_salary': 327900, 'employee_age': 55, 'profile_image': ''}, {'id': 9, 'employee_name': 'Colleen Hurst', 'employee_salary': 205500, 'employee_age': 39, 'pro

In [184]:
#Task 1: find employee with age under 25
count =0
for d in list1:
    if(d.age < 25):
        count += 1
print('Employee under 25 : ',count)

Employee under 25 :  6


In [185]:
#task 2 : How many earn > 40000
count =0
for d in list1:
    if(d.salary > 40000):
        count += 1
print('Employee With Earning more than 40000 : ',count)
#print(len(data['data']))
#file.close()

Employee With Earning more than 40000 :  24


In [186]:
#Task 3 : Do older earn more
count1 = 0
count2 = 0
for d in list1:
    if(d.salary>40000 and d.age>25):
        count1 += 1
    elif(d.salary<40000 and d.age>25):
        count2 += 1
print('Olders Earning more are :',count1)
print('Olders Earning less are :',count2)
if(count1>count2):
    print('Olders earns more')
#print(len(data['data']))
#file.close()

Olders Earning more are : 18
Olders Earning less are : 0
Olders earns more


In [195]:
#exercise 2:
#POST
list2 = []
for emp in employees:
    #id = emp['id']
    name= emp['employee_name']
    age = emp['employee_age']
    #salary = emp['employee_salary']
    emp = (name,age)
    #print(emp)
    list2.append(emp)

url ="http://httpbin.org/post"
p = r.post(url,data=list2)
if(p.status_code == 200):
    data = p.json()
    print('Header  : ',data['headers'])
    print('Content-Type : ',data['headers']['Content-Type'])
    print('Form  :',data['form'])

Header  :  {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Length': '399', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.27.1', 'X-Amzn-Trace-Id': 'Root=1-6309123a-4fbc3a2e5cb72288230dfa55'}
Content-Type :  application/x-www-form-urlencoded
Form  : {'Airi Satou': '33', 'Ashton Cox': '66', 'Bradley Greer': '41', 'Brielle Williamson': '61', 'Caesar Vance': '21', 'Cedric Kelly': '22', 'Charde Marshall': '36', 'Colleen Hurst': '39', 'Dai Rios': '35', 'Doris Wilder': '23', 'Garrett Winters': '63', 'Gloria Little': '59', 'Haley Kennedy': '43', 'Herrod Chandler': '59', 'Jena Gaines': '30', 'Jenette Caldwell': '30', 'Michael Silva': '66', 'Paul Byrd': '64', 'Quinn Flynn': '22', 'Rhona Davidson': '55', 'Sonya Frost': '23', 'Tatyana Fitzpatrick': '19', 'Tiger Nixon': '61', 'Yuri Berry': '40'}


In [188]:
#Task 3 : Do older earn more (Better Version)
from statistics import mean as mn
count1 = 0
count2 = 0
sal_olders = []
sal_younger = []
for d in list1:
    if(d.age>25):
        sal_olders.append(d.salary)
    else:
        sal_younger.append(d.salary)
if(mn(sal_younger)>mn(sal_olders)):
    print('No! Olders does not earn more')
else:
    print('Olders earns more')
#--------------------------------------------------
print(mn(sal_olders))
print(mn(sal_younger))
print("Olders : ",sal_olders)
print("Youngers : ",sal_younger)
#---------------------------------------


#print(len(data['data']))
#file.close()

Olders earns more
288239.44444444444
242743.33333333334
Olders :  [320800, 170750, 86000, 162700, 372000, 137500, 327900, 205500, 90560, 470600, 313500, 198500, 725000, 237500, 132000, 217500, 345000, 675000]
Youngers :  [433060, 103600, 342000, 385750, 106450, 85600]


In [ ]:
#Unit Testing
import unittest 
#import Error

def join_names(first, last):
    return ' '.join([first.capitalize(), last.capitalize()])


return_data =  join_names('ahmed', 'raza')
print(return_data)


class TestStringMethods(unittest.TestCase):
    def test_is_capitalized(self):
        temp1, temp2 = return_data.split(' ')
        self.assertTrue(temp1.istitle())
        self.assertTrue(temp2.istitle())
    
    def test_length(self):
        self.assertTrue(len(return_data.split(' ')), 2)
    
    def test_split(self):
        self.assertEqual(type(return_data), str)

try:
    if __name__ == '__main__':
        unittest.main()
except Error as  e:
    print(e)

In [ ]:
import pdb

def sum_values(a, b):
    return a + b

def test_function():
    pdb.set_trace()  #we have added a breakpoint here. The code pause execution here.
    print('This is the first line')
    print("This is the second line.")
    value  = sum_values(2, 3)
    print('The code is done!')
    return value 


test_function()


In [1]:
#testing & debugging exercise:1
import pdb
class Calculator:
    def addNum(num1 , num2):
        pdb.set_trace()
        print('Add Method has been called')
        value = num1 + num2
        print('Add Method has been operated')
        return value
    
    def subNum(num1 , num2):
        pdb.set_trace()
        print('Sub Method has been called')
        value = num1 - num2
        print('Sub Method has been operated')
        return value
    
    def mulNum(num1 , num2):
        pdb.set_trace()
        print('Mul Method has been called')
        value = num1 * num2
        print('Mul Method has been operated')
        return value
    
    def divNum(num1 , num2):
        pdb.set_trace()
        print('Div Method has been called')
        value = num1 / num2
        print('Div Method has been operated')
        return value
    
    def powNum(num1 , num2):
        pdb.set_trace()
        print('Pow Method has been called')
        value = num1 ** num2
        print('Div Method has been operated')
        return value
    
    def modNum(num1 , num2):
        pdb.set_trace()
        print('Mod Method has been called')
        value = num1 % num2
        print('Div Method has been operated')
        return value
x = 2
y = 3
return_add = Calculator.addNum(x,y)
return_sub = Calculator.subNum(x,y)
return_mul = Calculator.mulNum(x,y)
return_div = Calculator.divNum(x,y)
return_pow = Calculator.powNum(x,y)
return_mod = Calculator.modNum(x,y)
print('Results : ')
print('Addition : ',return_add)
print('Subtraction : ',return_sub)
print('Multiplication : ',return_mul)
print('Division  ',return_div)
print('Power : ',return_pow)
print('Modulus : ',return_mod)

#Testing
import unittest
#test cases
class testCalculations(unittest.TestCase):
    def testAdd(self):
        self.assertTrue(isinstance(return_add, int))
    def testSub(self):
        self.assertTrue(isinstance(return_sub, int))
    def testMul(self):
        self.assertTrue(isinstance(return_mul, int))
    def testDiv(self):
        self.assertTrue(isinstance(return_div, float))
    def testPow(self):
        self.assertTrue(isinstance(return_pow, int))
    def testMod(self):
        self.assertTrue(isinstance(return_mod, int))
#Exe Tests        
if __name__ == '__main__':
        unittest.main()
        
#Use case for fail
return_add = 2.3
return_sub =3.2
return_mul = '3'
return_div = 2
return_pow = "3"
return_mod = Calculator()

if __name__ == '__main__':
        unittest.main()        

> c:\users\momin-pc\appdata\local\temp\ipykernel_11368\4170168644.py(6)addNum()

ipdb> c
Add Method has been called
Add Method has been operated
> c:\users\momin-pc\appdata\local\temp\ipykernel_11368\4170168644.py(13)subNum()

ipdb> c
Sub Method has been called
Sub Method has been operated
> c:\users\momin-pc\appdata\local\temp\ipykernel_11368\4170168644.py(20)mulNum()

ipdb> c
Mul Method has been called
Mul Method has been operated
> c:\users\momin-pc\appdata\local\temp\ipykernel_11368\4170168644.py(27)divNum()

ipdb> c
Div Method has been called
Div Method has been operated
> c:\users\momin-pc\appdata\local\temp\ipykernel_11368\4170168644.py(34)powNum()

ipdb> c
Pow Method has been called
Div Method has been operated
> c:\users\momin-pc\appdata\local\temp\ipykernel_11368\4170168644.py(41)modNum()

ipdb> c


E
ERROR: C:\Users\Momin-PC\AppData\Roaming\jupyter\runtime\kernel-93fc5483-471f-4c9a-8e5d-e83eabcbfe60 (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute 'C:\Users\Momin-PC\AppData\Roaming\jupyter\runtime\kernel-93fc5483-471f-4c9a-8e5d-e83eabcbfe60'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)


Mod Method has been called
Div Method has been operated
Results : 
Addition :  5
Subtraction :  -1
Multiplication :  6
Division   0.6666666666666666
Power :  8
Modulus :  2


SystemExit: True

C:\Users\Momin-PC\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3377: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [1]:
#mahi
def add(x,y):
    return x % y
count  = 0
x = 4
y = (5/9)
while(count<2):
    print('Result : ',add(x,y))
    x += 1
    y += 1
    count += 1

Result :  0.11111111111111094
Result :  0.33333333333333326


In [ ]:
#Decorators : Wrap
def extract_function_name(func): 
     def internal_method(*args, **kwargs): 
         print('The method called is:', func.__name__)
         returned_value = func(*args, **kwargs)
         print('The method execution is complete.')
         return returned_value 
     return internal_method
  
# # adding decorator to the function 
@extract_function_name
def sum_two_numbers(a, b): 
    print("This is called inside the function") 
    return a + b 

@extract_function_name
def product_two_numbers(a, b): 
    print("This is called inside the function") 
    return a * b 

a, b = 3, 4
# getting the value through return of the function 
print('Sum function value:', sum_two_numbers(a, b))
print('Product function value', product_two_numbers(a, b))

In [ ]:
#Decorators Practice
#WrapperFunction
def validateInput(func):
    def check(*args,**kargs):
        print("The method called is : ",func.__name__)
        #write on file : log
        returned_value = func(*args,**kargs)
        print('Execution of the method is completed')
        return returned_value
    return check

#WrappingFunctions
@validateInput
def productOp(x,y):
    return x * y
@validateInput    
def divOp(x,y):
    return x /y

#Work
x = 2
y = 3
print("Product of {} and {} is {}".format(x,y,productOp(x,y)))
print("DivisionProduct of {} and {} is {}".format(x,y,divOp(x,y)))
 

In [ ]:
def my_power_raiser(n):
  return lambda a : a ** n

square_it = my_power_raiser(2)
cube_it = my_power_raiser(3)
quad_it = my_power_raiser(4)

input_number = 3
print('Our input is:', input_number)
print('square_it function raises input by power 2: ', square_it(input_number))
print('cube_it function raises input by power 3: ', cube_it(input_number))
print('quad_it function raises input by power 4: ', quad_it(input_number))

In [2]:
import inspect as ins
def func1():
    return 2 * 3
dtrf = "a"
ins.getmembers(dtrf)

[('__add__', <method-wrapper '__add__' of str object at 0x0000013165F2D530>),
 ('__class__', str),
 ('__contains__',
  <method-wrapper '__contains__' of str object at 0x0000013165F2D530>),
 ('__delattr__',
  <method-wrapper '__delattr__' of str object at 0x0000013165F2D530>),
 ('__dir__', <function str.__dir__()>),
 ('__doc__',
  "str(object='') -> str\nstr(bytes_or_buffer[, encoding[, errors]]) -> str\n\nCreate a new string object from the given object. If encoding or\nerrors is specified, then the object must expose a data buffer\nthat will be decoded using the given encoding and error handler.\nOtherwise, returns the result of object.__str__() (if defined)\nor repr(object).\nencoding defaults to sys.getdefaultencoding().\nerrors defaults to 'strict'."),
 ('__eq__', <method-wrapper '__eq__' of str object at 0x0000013165F2D530>),
 ('__format__', <function str.__format__(format_spec, /)>),
 ('__ge__', <method-wrapper '__ge__' of str object at 0x0000013165F2D530>),
 ('__getattribute__',

In [3]:
import math as m
def traceTask(func):
    def calOperation(*args,**kargs):

        returned_value = func(*args,**kargs)
        length = args.__len__()
        funcName = ins.getsource(func).split()
        operation = getOperation(funcName)
        print("The Method Called is : ",operation[1])
        if(length == 2):
            print(f"Operation : {args[0]} " + operation[0] + f" {args[1]}  :  =",returned_value)
        else:
            print(f"Operation : {args[0]} " + operation[0] +" =",returned_value)
        
        print('Execution of the method is completed\n')
        return returned_value
    return calOperation

class Calculator:
    @traceTask
    def addedInto (num1 , num2):
        return num1 + num2
    @traceTask
    def subtractedBy (num1 , num2):
        return num1 - num2
    @traceTask
    def multipliedBy (num1 , num2):
        return num1 * num2
    @traceTask
    def dividedBy (num1 , num2):
        return num1 / num2

class ScientificCalculator(Calculator):
    log = traceTask(lambda x : m.log(x))
    power = traceTask(lambda x,y : x ** y)
    exponent = traceTask(lambda x : m.exp(x))
    factorial = traceTask(lambda x : m.factorial(x))

def getOperation(operation):
    if "addedInto" in operation[2]:
        return ["+",operation[2]]
    elif "multipliedBy" in operation[2]:
        return ["*",operation[2]]
    elif "subtractedBy" in operation[2]:
        return ["-",operation[2]]
    elif "dividedBy" in operation[2]:
        return ["/",operation[2]]
    elif "log" in operation[0]:
        return ["log",operation[0]]
    elif "power" in operation[0]:
        return ["^",operation[0]]
    elif "factorial" in operation[0]:
        return ["!",operation[0]]
    elif "exponent" in operation[0]:
        return ["E",operation[0]]            

ScientificCalculator.factorial(4)
ScientificCalculator.power(3,3)
ScientificCalculator.log(10)
ScientificCalculator.exponent(4)
ScientificCalculator.addedInto(2,2)
ScientificCalculator.multipliedBy(9,7)
ScientificCalculator.subtractedBy(89,56)
ScientificCalculator.dividedBy(9,18)

The Method Called is :  factorial
Operation : 4 ! = 24
Execution of the method is completed

The Method Called is :  power
Operation : 3 ^ 3  :  = 27
Execution of the method is completed

The Method Called is :  log
Operation : 10 log = 2.302585092994046
Execution of the method is completed

The Method Called is :  exponent
Operation : 4 E = 54.598150033144236
Execution of the method is completed

The Method Called is :  addedInto
Operation : 2 + 2  :  = 4
Execution of the method is completed

The Method Called is :  multipliedBy
Operation : 9 * 7  :  = 63
Execution of the method is completed

The Method Called is :  subtractedBy
Operation : 89 - 56  :  = 33
Execution of the method is completed

The Method Called is :  dividedBy
Operation : 9 / 18  :  = 0.5
Execution of the method is completed



0.5

In [5]:
import cProfile 

def internal_method():
    temp_var = 0
    for ind in range(10000):
        temp_var += 1
    return temp_var

def external_method():
    counter = 0
    for val in range(10):
        counter += internal_method()
    print('Total iterations:', counter)
    return 

cProfile.run('external_method()')

Total iterations: 100000
         79 function calls in 0.017 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       10    0.016    0.002    0.016    0.002 3874921366.py:3(internal_method)
        1    0.000    0.000    0.017    0.017 3874921366.py:9(external_method)
        1    0.000    0.000    0.017    0.017 <string>:1(<module>)
        5    0.000    0.000    0.000    0.000 iostream.py:208(schedule)
        4    0.000    0.000    0.000    0.000 iostream.py:420(_is_master_process)
        4    0.000    0.000    0.000    0.000 iostream.py:439(_schedule_flush)
        4    0.000    0.000    0.000    0.000 iostream.py:502(write)
        5    0.000    0.000    0.000    0.000 iostream.py:97(_event_pipe)
        5    0.000    0.000    0.000    0.000 socket.py:480(send)
        5    0.000    0.000    0.000    0.000 threading.py:1059(_wait_for_tstate_lock)
        5    0.000    0.000    0.000    0.000 threading.py:1126(is_alive)


In [16]:
import math as m
import inspect as ins
import cProfile as cP
def traceTask(func):
    def calOperation(*args,**kargs):

        returned_value = func(*args,**kargs)
        length = args.__len__()
        funcName = ins.getsource(func).split()
        operation = getOperation(funcName)
        print("The Method Called is : ",operation[1])
        if(length == 2):
            print(f"Operation : {args[0]} " + operation[0] + f" {args[1]}  :  =",returned_value)
        else:
            print(f"Operation : {args[0]} " + operation[0] +" =",returned_value)
        
        print('Execution of the method is completed\n')
        return returned_value
    return calOperation

class Calculator:
    @traceTask
    def addedInto (num1 , num2):
        return num1 + num2
    @traceTask
    def subtractedBy (num1 , num2):
        return num1 - num2
    @traceTask
    def multipliedBy (num1 , num2):
        return num1 * num2
    @traceTask
    def dividedBy (num1 , num2):
        return num1 / num2

class ScientificCalculator(Calculator):
    log = traceTask(lambda x : m.log(x))
    power = traceTask(lambda x,y : x ** y)
    exponent = traceTask(lambda x : m.exp(x))
    factorial = traceTask(lambda x : m.factorial(x))

def getOperation(operation):
    if "addedInto" in operation[2]:
        return ["+",operation[2]]
    elif "multipliedBy" in operation[2]:
        return ["*",operation[2]]
    elif "subtractedBy" in operation[2]:
        return ["-",operation[2]]
    elif "dividedBy" in operation[2]:
        return ["/",operation[2]]
    elif "log" in operation[0]:
        return ["log",operation[0]]
    elif "power" in operation[0]:
        return ["^",operation[0]]
    elif "factorial" in operation[0]:
        return ["!",operation[0]]
    elif "exponent" in operation[0]:
        return ["E",operation[0]]            


def performOperations1():
    sc = ScientificCalculator
    sc.factorial(4)
    sc.power(3,3)
    sc.log(10)
    sc.exponent(4)
    sc.addedInto(2,2)
    sc.multipliedBy(9,7)
    sc.subtractedBy(89,56)
    sc.dividedBy(9,18)

cP.run("performOperations1()")


def performOperations2():
    sc = ScientificCalculator
    sc.factorial(4)
    sc.power(3,3)
    sc.log(10)
    sc.exponent(4)
    sc.addedInto(2,2)
    sc.multipliedBy(9,7)
    sc.subtractedBy(89,56)
    sc.dividedBy(9,18)

cP.run("performOperations2()")

The Method Called is :  factorial
Operation : 4 ! = 24
Execution of the method is completed

The Method Called is :  power
Operation : 3 ^ 3  :  = 27
Execution of the method is completed

The Method Called is :  log
Operation : 10 log = 2.302585092994046
Execution of the method is completed

The Method Called is :  exponent
Operation : 4 E = 54.598150033144236
Execution of the method is completed

The Method Called is :  addedInto
Operation : 2 + 2  :  = 4
Execution of the method is completed

The Method Called is :  multipliedBy
Operation : 9 * 7  :  = 63
Execution of the method is completed

The Method Called is :  subtractedBy
Operation : 89 - 56  :  = 33
Execution of the method is completed

The Method Called is :  dividedBy
Operation : 9 / 18  :  = 0.5
Execution of the method is completed

         3632 function calls in 0.012 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000

In [20]:
from lxml import etree

def parseBookXML(xmlFile):
    with open(xmlFile) as fobj:
        xml = fobj.read()
    root = etree.fromstring(xml)
    book_dict = {}
    books = []
    for book in root.getchildren():
        for elem in book.getchildren():
            if elem.text:
                text = elem.text
            else:
                text = ''
            if elem.tag == 'author':
                last_name, first_name = text.split(',')
                print(elem.tag + ':', first_name, last_name)
            else:
                print(elem.tag + ": " + text)
            book_dict[elem.tag] = text
        if book.tag == "book":
            books.append(book_dict)
            book_dict = {}
        print("\n")    
    return books

my_books = parseBookXML("E:\\Python\\books.xml")

author:  Matthew Gambardella
title: XML Developer's Guide
genre: Computer
price: 44.95
publish_date: 2000-10-01
description: An in-depth look at creating applications 
      with XML.


author:  Kim Ralls
title: Midnight Rain
genre: Fantasy
price: 5.95
publish_date: 2000-12-16
description: A former architect battles corporate zombies, 
      an evil sorceress, and her own childhood to become queen 
      of the world.


author:  Eva Corets
title: Maeve Ascendant
genre: Fantasy
price: 5.95
publish_date: 2000-11-17
description: After the collapse of a nanotechnology 
      society in England, the young survivors lay the 
      foundation for a new society.


author:  Eva Corets
title: Oberon's Legacy
genre: Fantasy
price: 5.95
publish_date: 2001-03-10
description: In post-apocalypse England, the mysterious 
      agent known only as Oberon helps to create a new life 
      for the inhabitants of London. Sequel to Maeve 
      Ascendant.


author:  Eva Corets
title: The Sundered Grail
gen

In [40]:
#LXML Exercise
from lxml import etree
def parseBookXML(xmlFile):
    with open(xmlFile) as fobj:
        xml = fobj.read()
    root = etree.fromstring(xml)
    food_dict = {}
    foods = []
    for food in root.getchildren():
        for elem in food.getchildren():
            if elem.text:
                text = elem.text
            else:
                text = ''
            print(elem.tag + ": " + text)
            food_dict[elem.tag] = text
        if food.tag == "food":
            foods.append(food_dict)
            food_dict = {}
        print("\n")    
    return foods

my_foods = parseBookXML("E:\\Python\\foods.xml")
print(my_foods)

name: Belgian Waffles
price: $5.95
description: Two of our famous Belgian Waffles with plenty of real maple syrup
calories: 650


name: Strawberry Belgian Waffles
price: $7.95
description: Light Belgian waffles covered with strawberries and whipped cream
calories: 900


name: Berry-Berry Belgian Waffles
price: $8.95
description: Light Belgian waffles covered with an assortment of fresh berries and whipped cream
calories: 900


name: French Toast
price: $4.50
description: Thick slices made from our homemade sourdough bread
calories: 600


name: Homestyle Breakfast
price: $6.95
description: Two eggs, bacon or sausage, toast, and our ever-popular hash browns
calories: 950


[{'name': 'Belgian Waffles', 'price': '$5.95', 'description': 'Two of our famous Belgian Waffles with plenty of real maple syrup', 'calories': '650'}, {'name': 'Strawberry Belgian Waffles', 'price': '$7.95', 'description': 'Light Belgian waffles covered with strawberries and whipped cream', 'calories': '900'}, {'name':

In [79]:
### Read Text/String file ###
sample_config = """
[Settings]
user = username
profile = /my/directory/to/profile.png
gender = male
[My new Settings]
user = moh
profile = /my/directory/to/profile.png
gender = female
"""
# creates an instance of ConfigParser called parser 
parser = configparser.ConfigParser()  

#read the instance of string using read_string() method
parser.read_string(sample_config)

parser.sections()  #['My Settings']
user = parser["My new Settings"]["user"]  #'username'
print(user)
[option for option in parser['Settings']]

moh


['user', 'profile', 'gender']

In [44]:
### Read INI file ###
import configparser

parser = configparser.ConfigParser()
parser.read("C:\\Users\\Momin-PC\\.spyder-py3\\config\\spyder.ini")
parser.sections()
[option for option in parser['help']]

['enable',
 'max_history_entries',
 'wrap',
 'connect/editor',
 'connect/ipython_console',
 'math',
 'automatic_import',
 'plain_mode',
 'rich_mode',
 'show_source',
 'locked']

In [48]:
### Create Dictionaru ###
parser = configparser.ConfigParser()
parser.read_dict(
    {'section1': 
        {'tag1': '1','tag2': '2','tag3': '3'},
    'section2': 
        {'tagA': 'A','tagB': 'B','tagC': 'C'},
    'section3': 
        {'foo': 'x','bar': 'y','baz': 'z'} })
parser.sections()  #['section1', 'section2', 'section3']
[option for option in parser['section1']] # ['foo', 'bar', 'baz']

['tag1', 'tag2', 'tag3']

In [50]:
str1 = "momin ki Jaan"
str1

'momin ki Jaan'

In [57]:
str1 = "momin ki Jaan"
str1
str2 = "momin ki ***"
str2

'momin ki ***'

In [98]:
#Exercise 1 : Config Parser
### Read from file using path ###
import configparser

parser = configparser.ConfigParser()
parser.read("E:\\python\\config.txt")
sections = parser.sections()
for sec in sections:
    print(sec,": ",parser.items(sec)) 
print("\n")    
for sec in sections:
    for key,value in parser.items(sec):
        print(key,": ",value)

root_Directory :  [('dir', 'E:\\Python\\temp')]
username :  [('name', 'momin')]
Num_of_db_connected :  [('num', '1128')]
summmary_unit :  [('units', '[3.7,8.9,0.3]')]


dir :  E:\Python\temp
name :  momin
num :  1128
units :  [3.7,8.9,0.3]


In [102]:
#Exercise 1 : Config Parser
### Read from Dictionaruy ###
import configparser
parser = configparser.ConfigParser()
parser.read_dict(
    {'root_Directory': {'dir1': 'E:\\Python\\temp','tag2': '2','tag3': '3'},
    'username': {'name': 'momin','tagB': 'B','tagC': 'C'},
    'Num_of_db_connected': {'num':'1128'},
     'summary_units': {'units': '[3.7,8.9,0.3]','bar': '[3.7,8.9,0.3]','baz': '[3.7,8.9,0.3]'}
    })
sections = parser.sections()  
for sec in sections:
    print(sec,":")
    for key,value in parser.items(sec):
        print(key,": ",value)
    print("\n")    

root_Directory :
dir1 :  E:\Python\temp
tag2 :  2
tag3 :  3


username :
name :  momin
tagb :  B
tagc :  C


Num_of_db_connected :
num :  1128


summary_units :
units :  [3.7,8.9,0.3]
bar :  [3.7,8.9,0.3]
baz :  [3.7,8.9,0.3]




In [109]:
#Exercise 1 : Config Parser
### Read from String ###
import configparser
parser = configparser.ConfigParser()
parser.read_string('''
[root_Directory]
dir1 = E:\Python\\temp
tag2 =  2
tag3 =  3
[username]
name =  momin
tagb =  B
tagc =  C
[Num_of_db_connected]
num = 1128
[summary_units]
units =  [3.7,8.9,0.3]
bar =  [3.7,8.9,0.3]
baz =  [3.7,8.9,0.3]
''')
sections = parser.sections()  
for sec in sections:
    print(sec,":")
    for key,value in parser.items(sec):
        print(key,": ",value)

root_Directory :
dir1 :  E:\Python\temp
tag2 :  2
tag3 :  3
username :
name :  momin
tagb :  B
tagc :  C
Num_of_db_connected :
num :  1128
summary_units :
units :  [3.7,8.9,0.3]
bar :  [3.7,8.9,0.3]
baz :  [3.7,8.9,0.3]


In [114]:
#Exercise 1 : Config Parser
### Read from file ###
import configparser
parser = configparser.ConfigParser()
file = open("C:\\Users\\Momin-PC\\.spyder-py3\\config\\spyder.ini","r")
parser.read_file(file)
sections = parser.sections() 
for sec in sections:
    print(sec,":")
    for key,value in parser.items(sec):
        print(key,": ",value)
    print("\n")   

main :
opengl :  software
single_instance :  True
open_files_port :  21128
mac_open_file :  False
normal_screen_resolution :  True
high_dpi_scaling :  False
high_dpi_custom_scale_factor :  False
high_dpi_custom_scale_factors :  1.5
vertical_tabs :  False
prompt_on_exit :  False
panes_locked :  True
window/is_maximized :  True
window/is_fullscreen :  False
use_custom_margin :  True
custom_margin :  0
use_custom_cursor_blinking :  False
show_internal_errors :  True
check_updates_on_startup :  True
cursor/width :  2
report_error/remember_token :  False
show_dpi_message :  True
version :  70.1.0
previous_crash :  
window/statusbar :  True


toolbar :
enable :  True
toolbars_visible :  True


statusbar :
show_status_bar :  True
memory_usage/enable :  True
memory_usage/timeout :  2000
cpu_usage/enable :  False
cpu_usage/timeout :  2000
clock/enable :  False
clock/timeout :  1000


internal_console :
max_line_count :  300
working_dir_history :  30
working_dir_adjusttocontents :  False
wrap : 

spyder/matched_p :  #99ff99
spyder/unmatched_p :  #ff9999
spyder/normal :  ('#000000', False, False)
spyder/keyword :  ('#0000ff', False, False)
spyder/magic :  ('#0000ff', False, False)
spyder/builtin :  ('#900090', False, False)
spyder/definition :  ('#000000', True, False)
spyder/comment :  ('#adadad', False, True)
spyder/string :  ('#00aa00', False, False)
spyder/number :  ('#800000', False, False)
spyder/instance :  ('#924900', False, True)
spyder/dark/name :  Spyder Dark
spyder/dark/background :  #19232D
spyder/dark/currentline :  #3a424a
spyder/dark/currentcell :  #292d3e
spyder/dark/occurrence :  #1A72BB
spyder/dark/ctrlclick :  #179ae0
spyder/dark/sideareas :  #222b35
spyder/dark/matched_p :  #0bbe0b
spyder/dark/unmatched_p :  #ff4340
spyder/dark/normal :  ('#ffffff', False, False)
spyder/dark/keyword :  ('#c670e0', False, False)
spyder/dark/magic :  ('#c670e0', False, False)
spyder/dark/builtin :  ('#fab16c', False, False)
spyder/dark/definition :  ('#57d6e4', True, False)
sp

In [174]:
#threading
import datetime
import threading 
  
def get_cubic(num): 
    print(datetime.datetime.now(),"\n")
    print("Cube: {}".format(num * num * num)) 
  
def get_inverse(num):
    print(datetime.datetime.now())
    print("Inverted: {}".format(1 / num)) 
  
if __name__ == "__main__": 
    # creating thread 
    t1 = threading.Thread(target=get_cubic, args=(10,))  
    t2 = threading.Thread(target=get_inverse, args=(10,)) 
#     # Starting the threads 
    t1.start() 
    t2.start()
#     # waiting for each to finish  
    t1.join() 
    t2.join() 
#     # both threads completely executed 
    print("Done!") 

2022-08-31 03:10:37.132262 

Cube: 1000
2022-08-31 03:10:37.136251
Inverted: 0.1
Done!


In [5]:
######################## QUESTION 3: THREADING ########################
# You are required to conduct analysis on data obtained from a plant related to temperature readings. 
# The file temperatures.csv contains the appropriate data required for this task.
# Write methods to generate:
#   1. Average time lapse in readings
#   2. Average per hour temperature recording
#   3. Largest spike in data (percentage)
#   4. Overall deviation in the data 

# Conduct the above calculations through two threads (each thread conducts two calculations). 
# Measure up time with and without threads. Log your results in section_four/temperature.txt using the appropriate library.

# SOLUTION STARTS HERE #
import logging
import time
import datetime 
import threading 
import csv 
# read file from csv 
file = "E://python//temperature-200423-032315.csv"
garbage_value = ''
data = {}

# read data 
temp_list = []
time_list = []
with open(file, "r") as f:
    reader = csv.reader(f)
    f.__next__()
    for row in reader:
        time_check, temp = row
        if garbage_value in time_check:
            time_check = time_check.replace(garbage_value, '')
        time_check = datetime.datetime.strptime(time_check, '%H:%M:%S')
        temp = float(temp)
        temp_list.append(temp)
        time_list.append(time_check)
f.close()

# define method for time lapse 
def caclulate_time_lapse(time_data):
    assert type(time_data) == list 
    all_time_lapses = []
    for ind in range(len(time_data)):
        if ind == 0:
            continue 
        lapse = (time_data[ind] - time_data[ind-1]).total_seconds() # .total_seconds() gives the difference in seconds as a numeric value 
        all_time_lapses.append(lapse) 
    avg_time_lapse = sum(all_time_lapses)/len(all_time_lapses)
    return avg_time_lapse

# define method for largest spike in temperature 
def calculate_largest_spike(temperature_data):
    pct_change = []
    for ind in range(len(temperature_data)):
        if ind == 0:
            continue 
        diff = (temperature_data[ind] - temperature_data[ind-1])/temperature_data[ind-1]
        pct_change.append(diff)
    return max(pct_change)

# define method for calculating hourly temperature 
def calculate_hourly_temperature(time_data, temp_data):
    # for a datetime object x, x.hour gives the hour value. We collect together same hour temperature values and take average
    time_in_hours = [time_val.hour for time_val in time_data]
    unique_hours = set(time_in_hours) # set() converts a list into a set of unique elements   
    avg_readings = []
    for unique_hour in unique_hours:
        hour_readings = []
        for ind in range(len(time_in_hours)):
            if time_in_hours[ind] == unique_hour:
                hour_readings.append(temp_list[ind])
        avg = sum(hour_readings)/len(hour_readings)
        avg_readings.append(round(avg, 2)) # rounding up to 2  decimal value for sake of ease of reading.
    return avg_readings

# define method for calculating standard deviation in temperature 
# the formula for deviation (standard deviation) is: square_root(sum((x - x_mean)^2)/total_obs)
def calculate_deviation_temperature(temperature_data):
    avg_temperature = sum(temperature_data)/len(temperature_data)
    total_observations = len(temperature_data)
    sq_diff = []
    for value in temperature_data:
        calc = (value - avg_temperature)**2
        sq_diff.append(calc)
    sum_squared_avg = sum(sq_diff)/total_observations
    standard_deviation = sum_squared_avg**(0.5)
    return standard_deviation

# define method for first thread calculations
def first_thread_function():
    tl = caclulate_time_lapse(time_list)
    print('The time lapse is:', tl)
    ls = calculate_largest_spike(temp_list)
    print('The largest spike in temperature is:', ls)
    return 

# define method for second thread calculations 
def second_thread_function():
    av_temp = calculate_hourly_temperature(time_list, temp_list)
    print('Average hourly temperatures are ', av_temp)
    std = calculate_deviation_temperature(temp_list)
    print('Deviation in temperature is: ', std)
    return 

def get_time(start, end):
    return round(end - start, 10)

def main():
    # creating thread 
    start = time.time()
    t1 = threading.Thread(target=first_thread_function) 
    t2 = threading.Thread(target=second_thread_function) 
    # # Starting the threads 
    t1.start() 
    t2.start()
    # # waiting for each to finish  
    t1.join() 
    t2.join() 
    # # both threads completely executed 
    end = time.time()
    print('With threading it took: {} seconds.'.format(get_time(start, end)))
    start2 = time.time()
    first_thread_function()
    second_thread_function()
    end2 = time.time()
    print('Without threading it took: {} seconds'.format(get_time(start2, end2)))
# SOLUTION END HERE #

main()

    

The time lapse is: 560.0
The largest spike in temperature is: 1.3157894736842104
Average hourly temperatures are  [19.87, 16.83, 15.7]
Deviation in temperature is:  5.2230109850545015
With threading it took: 0.0039885044 seconds.
The time lapse is: 560.0
The largest spike in temperature is: 1.3157894736842104
Average hourly temperatures are  [19.87, 16.83, 15.7]
Deviation in temperature is:  5.2230109850545015
Without threading it took: 0.0 seconds


In [6]:
def getAvgTemperature(file):
    dataFile.seek(0)
    temps = [float(temp[1]) for temp in file]
    return s.mean(temps)
  
def getAvgLapse(file):
    dataFile.seek(0)
    file.__next__()
    lapses = [lapse[0] for lapse in file]
   
    length = lapses.__len__()
    lapseFirst = dtClass.strptime(lapses[0],"%H:%M:%S")
    lapseLast = dtClass.strptime(lapses[length - 1],"%H:%M:%S")
    lapseDifference = (lapseLast - lapseFirst).seconds
    return lapseDifference/length
#avg_temperature = sum(tempList)/len(tempList)
    #total_observations = len(tempList)
    #sq_diff = []
    #for value in tempList:
        #calc = (value - avg_temperature)**2
        #sq_diff.append(calc)
    #sum_squared_avg = sum(sq_diff)/total_observations
    #standard_deviation = sum_squared_avg**(0.5)
    #return standard_deviation
    # -*- coding: utf-8 -*-
"""
Created on Wed Aug 31 07:51:58 2022

@author: Momin-PC
"""

#Threading Exercise ---
import datetime as dt
from datetime import datetime as dtClass
import threading as th
import csv as c
import statistics as s
import cProfile as cP
import pstats
import io
border = "-" * 175 + "\n"
logFile = open('E:\\python\\temperature.txt','a')

def traceTask(func):
    def calOperation(*args,**kargs):
        logFile.write("The Method Called is : {}\n".format(func.__name__))
        pr = cP.Profile()
        pr.enable()
        returned_value = func(*args,**kargs)
        pr.disable()
        data = io.StringIO()
        ps = pstats.Stats(pr, stream=data).sort_stats('tottime')
        ps.print_stats()
        result = "Operation Result: {}\n".format(returned_value)
        log = data.getvalue()
        logFile.write(result)
        logFile.write(log)
        logFile.write('Execution of the method is completed\n')
        logFile.write(border)
        return result
    return calOperation

#get Data
filePath = "E:\\python\\temperature-200423-032315.csv"
dataFile = open(filePath)
file = c.reader(dataFile)
#rm header
file.__next__()
tempList = []
lapseList = []
for record in file:
    tempList.append(float(record[1]))
    lapseList.append(record[0])
@traceTask    
def avg_Temperature(temps):
    return s.mean(temps)
@traceTask  
def avg_Lapse(lapses):
    length = lapses.__len__()
    lapseFirst = dtClass.strptime(lapses[0],"%H:%M:%S")
    lapseLast = dtClass.strptime(lapses[length - 1],"%H:%M:%S")
    lapseDifference = (lapseLast - lapseFirst).seconds
    return lapseDifference/length
@traceTask
def largest_Spike(temps):
    spikes = []
    for index,temperature in enumerate(temps):
        if(index == temps.__len__()-1):continue
        spikes.append((temperature - temps[index+1])/temps[index+1] )
    return max(spikes)
@traceTask
def deviation(temps):
    return s.pstdev(temps)


def non_threading():
    start_time = dtClass.now()
    logFile.write(border+"Without Threading >> Starting at : ")
    logFile.write(str(start_time))
    logFile.write("\n"+border)
    calculateAvg(tempList,lapseList)
    calculateSharpness(tempList)
    end_time = dtClass.now()
    logFile.write(border+"Without Threading >> Ending at : ")
    logFile.write(str(end_time))
    logFile.write("\n"+border)
    time = (start_time - end_time).seconds
    return time
    #logFile.write(border+"Without Threading >> Ending at : "+end_time+"\n"+border)
    
def calculateAvg(tempList,lapseList):
    print('Average Temperature: ',avg_Temperature(tempList))
    print("Average Lapse Duration: ",avg_Lapse(lapseList))
def calculateSharpness(tempList):
    print("Largest Spikes: ",largest_Spike(tempList))
    print("Deviation: ",deviation(tempList))
    
def threading():
    start_time = dtClass.now()
    logFile.write(border+"Threading >> Starting at : ")
    logFile.write(str(start_time))
    logFile.write("\n"+border)
    logFile.write("Creating Thread No.1 >>\n Functions:\nave_Temperature\navg_Lapse")
    t1 = th.Thread(target=calculateAvg,args=(tempList,lapseList))
    logFile.write("Creating Thread No.2 >>\n Functions:\nlargets_Spike\ndeviation")
    t2 = th.Thread(target=calculateSharpness,args=(tempList,))
    logFile.write("Starting {}".format(t1))
    t1.start()
    logFile.write("Starting {}".format(t2))
    t2.start()
    logFile.write("Waiting for {} to finish".format(t1))
    t1.join()
    logFile.write("Waiting for {} to finish".format(t2))
    t2.join()
    end_time = dtClass.now()
    logFile.write(border+"Threading >> Ending at : ")
    logFile.write(str(end_time))
    logFile.write("\n"+border)
    time = (start_time - end_time).microseconds
    return time
    #logFile.write(border+"Threading >> Ending at : "+end_time+"\n"+border)
#Threading:
def main():
    s1 = str(non_threading())
    s2 = str(threading())
    logFile.write("Summary : \nTime Taken By Non-Threading Process :"+s1+"\nTime Taken By Threading Process :"+s2)
    logFile.close()
    
main()    
    

Average Temperature:  Operation Result: 17.6875

Average Lapse Duration:  Operation Result: 525.0

Largest Spikes:  Operation Result: 1.1538461538461537

Deviation:  Operation Result: 5.2230109850545015

Average Temperature: Largest Spikes:  Operation Result: 1.1538461538461537

 Operation Result: 17.6875
Deviation:  Operation Result: 5.2230109850545015


Average Lapse Duration:  Operation Result: 525.0



In [2]:
#moh
import numpy as np

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('The shape of matrix is : {}'.format(mat.shape))

newMat = mat.reshape(1,9)
print('The shape of new matrix is : {}'.format(newMat.shape))

transNewMat = newMat.T
print('The shape of trans new matrix is : {}'.format(transNewMat.shape))

diag = np.diag([1,2,3,4])
identity = np.identity(10)

seq = np.arange(0,100,5)

rands1d = np.random.rand(10)
rands2d = np.random.rand(10, 10)

myArray = np.array([1,3,5,7,23,6,2,31,5])
print('The max is {} at index {}'.format(myArray.max(), myArray.argmax()))
print('The min is {} at index {}'.format(myArray.min(), myArray.argmin()))

import time

myMatrix = np.random.rand(1000,1000)
anotherMatrix = np.random.rand(1000,1000)
start = time.time()
dotMul = myMatrix.dot(anotherMatrix)
end = time.time()
print('It took {} seconds to calculate dot product!'.format(round(end-start, 4)))

The shape of matrix is : (3, 3)
The shape of new matrix is : (1, 9)
The shape of trans new matrix is : (9, 1)
The max is 31 at index 7
The min is 1 at index 0
It took 0.0529 seconds to calculate dot product!


In [21]:
#numpy code
import numpy as np

mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
print('The shape of mat is:', mat.shape)
# it can be reshaped to any shape that is consistent with the data size
new_mat = mat.reshape(1,9)
print('The shape of new_mat is:', new_mat.shape)
# you can try transposing it as well.
trans_new_mat = new_mat.T
print('The transposed shape of new_mat is:', trans_new_mat.shape)

# you can create diagonal matrices, identity matrices
diag = np.diag([1,2,3,4])
print(diag)
identity = np.identity(5) # creates a 5 x 5 matrix with ones at diagonals and rest zeros 
print(identity)
# you can create arrays of random numbers or sequences 
seq = np.arange(start=0, stop=100, step=5) # creates an array starting from 0, with a step size of 5 till 100. [0,5,10,....,90,95]
# If you only pass np.random.rand(10), it creates a 1D vector of length 10
rands_1d = np.random.rand(10)
rands_2d = np.random.randn(2, 2) # creates 2x2 matrix with random numbers. 

# you can find min and max and min as well as the index of max number or min number 
my_array = np.array([1,3,5,7,23,6,2,31,5]) 
print('The max is {} at index {}'.format(my_array.max(), my_array.argmax()))
print('The min is {} at index {}'.format(my_array.min(), my_array.argmin()))

import time 
# you can perform dot products of matrices in a matter of seconds 
my_mat = np.random.rand(1000, 1000)
another_mat = np.random.rand(1000, 1000)
start = time.time()
# make sure the dimensions agree!
dot_mul = my_mat.dot(another_mat)
end = time.time()
print(dot_mul)
print('It took {} seconds to calculate dot product!'.format(round(end-start, 4)))

start = time.time()
prod = my_mat * another_mat
end = time.time()
print(prod)
print('It took {} seconds to calculate dot product!'.format(round(end-start, 4)))


The shape of mat is: (3, 3)
The shape of new_mat is: (1, 9)
The transposed shape of new_mat is: (9, 1)
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
The max is 31 at index 7
The min is 1 at index 0
[[248.49282928 262.04264646 247.90979879 ... 255.06365752 258.09975907
  242.68292922]
 [243.20246481 254.50824579 242.76732493 ... 247.64627103 249.92543066
  239.14509525]
 [235.75908844 245.58875045 235.17052828 ... 239.32183864 241.28430149
  225.24805426]
 ...
 [251.11873363 258.66735431 250.6720763  ... 250.38110264 259.70081605
  244.38978119]
 [239.14181553 261.5123575  242.45278321 ... 252.18350612 254.8511222
  247.37476637]
 [249.56113526 261.86234978 243.70086649 ... 245.63285209 260.38873101
  245.72583334]]
It took 0.0624 seconds to calculate dot product!
[[1.95901809e-01 5.79745297e-04 1.76501400e-01 ... 5.01238560e-01
  5.98312943e-01 1.58786288e-01]
 [8.09928561e-01 8.03802402e-04 3.441

In [16]:
import numpy as np
# linear algebra 
import numpy.linalg as la 

my_mat = np.array([[1,2],[3,4]])
# calculate determinant
det = la.det(my_mat)
print("Determinant: ",det)
# calculate inverse of a matrix. Inv = adj(matrix)/det(matrix). NOTE: Make sure its not SINGULAR!
inverse_mat = la.inv(my_mat)
print("Inverse: \n",inverse_mat)
# calculate eigen values. NOTE: make sure the matrix is SQUARE [eigen values do not exit for matrix whose dimensions are mxn where m!=n]!
eig_values, eig_vectors = la.eig(my_mat)
print("Eigen values: ",eig_values,"\nEigen vectors: \n",eig_vectors)
# calculate cholesky factorization. NOTE: make sure matrix is Positive Definite!
cholesky = la.cholesky(np.array([[7,2], [2,1]]))
print("cholesky factorization: \n",cholesky)
# calculate rank of a matrix. Rank of a matrix is the number of linearly independent columns/rows in a matrix.
rank = la.matrix_rank(my_mat)
print("Ranks: ",rank)


Determinant:  -2.0000000000000004
Inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigen values:  [-0.37228132  5.37228132] 
Eigen vectors: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
cholesky factorization: 
 [[2.64575131 0.        ]
 [0.75592895 0.65465367]]
Ranks:  2


In [50]:
#Numpy Exercise a: TYriangular Parts
import numpy as np
my_matrix = np.arange(5,85,5).reshape(4,4)
print("Lower part:\n",np.tril(my_matrix))
print("Upper part:\n",np.triu(my_matrix))

Lower part:
 [[ 5  0  0  0]
 [25 30  0  0]
 [45 50 55  0]
 [65 70 75 80]]
Upper part:
 [[ 5 10 15 20]
 [ 0 30 35 40]
 [ 0  0 55 60]
 [ 0  0  0 80]]


In [54]:
#Numpy Exercise b: Column Slicing
print(my_matrix)
print(my_matrix[:,1:3])

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [65 70 75 80]]
[[10 15]
 [30 35]
 [50 55]
 [70 75]]


In [120]:
#Numpy Exercise c: Count Occurence
matrix1 = np.random.randint(0,100,100)
count = 0
check_elements = 0
for element in matrix1:
    if(element == check_elements):
        count += 1
print(check_elements," occurred ,",count," times")
print(np.count_nonzero(matrix1 == 0))

0  occurred , 1  times
1


In [129]:
#Numpy Exercise d: Sum and Product
matrix1 = np.random.randint(5,10,4)
sumE = 0
prod = 1
for element in matrix1:
    sumE += element
    prod = prod * element
print("Sum of Elements: ",sumE)
print("Product of Elements: ",prod)
print(np.sum(matrix1))
print(np.product(matrix1))

Sum of Elements:  21
Product of Elements:  750
21
750


In [ ]:
#